# Import cattpuccin-mocha theme
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

shell.program = "/bin/zsh"

live_config_reload = true

[colors]
transparent_background_colors = true

# Leaving opacity alone here because I'm setting opacity directly from picom
# for slick transitions between focused/!focused
# --------------
[window]
padding.x = 20
padding.y = 10
# opacity = 0.85
# --------------

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono NerdFont"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NerdFont"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NerdFont"
style = "Italic"

[font.normal]
family = "JetBrains Mono NerdFont"
style = "Regular"
